### ISSUE TITLE
Malloc improvements

### ISSUE THREAD

**Issue by wipe2238** [ghost2238/sfall-asm#10]
```
//! NAME ???

//! SSL !//
call VOODOO_MakeCall(0x442c22, VOODOO_???__patch);
call VOODOO_WriteNop(0x442c22+5);
//! ASM !//
/// hook
[patch]  | 60            | pushad
// <insert crazy asm here>
00000000 | 61            | popad
/// restore
00000000 | 8915 CC865100 | mov dword ptr ds:[<_game_user_wants_to_quit>],edx
00000000 | C3            | ret
```
Just a stub, as i'm not quite sure where pointers array should be stored.

This is _almost_ same thing as `sfall::LoadGameHook::OnGameReset()`,  except there is no check if map has been loaded or not; it will be called when leaving main menu as well. So far can't find better place to `free()` malloc-patches.

**Comment by ghost2238** [comment]
As discussed on IRC, I think we can probably skip cleanup. 

We can add `VOODOO_nfree` to lib just in case but the better approach as you've mentioned is to malloc patches once, and then check if they are allocated or not by using macros that checks some state that's stored in the memory "managed by" sfall-asm since we can't rely on script variables to keep such state. 

We'd malloc a memory zone, keep a pointer to this allocated zone at some known place, like `0x00410003` and then put various variables and code at offsets to this base address.

The pointer to the address of the malloc'd area can be dereferenced by some macro in script if the pointer is not null, then the preallocated offsets can be used.

Something like this (the procedures should probably use VOODOO prefix):

```
variable malloc_address;
#define VOODOO_malloc_ptr             0x00410003
// Contains memory layout table
// Generated by sfall-asm
#define VOODOO_malloc_size            2000
#define VOODOO_var_SomePatchInit      0
#define VOODOO_var_AnotherPatchInit   1
#define VOODOO_patch_fill_w           1207
// Less raw access
#define VOODOO_IsSomePatchInit        read_malloc8(VOODOO_var_SomePatchInit) == 1

// Called first
procedure read_address begin
  malloc_address := read_int(VOODOO_malloc_ptr);
  return malloc_address;
end

// Then this
procedure malloc_init begin
   variable addr;
   if(malloc_address != 0) then
     return;
   addr := VOODOO_nmalloc(VOODOO_malloc_size);
   write_int(VOODOO_malloc_ptr, addr);
   call read_address();
end

// Finally we can use this.
// Generated malloc patches use these functions
procedure read_malloc8(variable offset) begin
   if(malloc_address == 0) then
      return -1;
   return read_byte(malloc_address+offset);
end

procedure write_malloc8(variable offset, variable value) begin
   if(malloc_address == 0) then
      return -1;
   write_byte(malloc_address+offset, value);
end

```

`read_address` and `malloc_init` are called from gl_0.

Let's wait until after release before implementing this though.

**Comment by wipe2238** [comment]
> We can add `VOODOO_nfree` to lib just in case

Oh! Oh! Don't forget `VOODOO_nrealloc`! 😄

Heh. While these functions might be unused by patches, they can be useful for scripts, i think. Either for testing, before code is mature enough for voodoo/_lib.h, code which is too specialized for them, scripts which barely have anything to do with 1@2, or simply scripts for personal use.

voodoo_lib could be, after all, used for generic Fallout2 scripts, either by careful coding (to not depend on 1@2 codecaves etc) or continue pushing it into higher level, which kinda happens naturally already.

**Comment by ghost2238** [comment]
Malloc handling in both sfall-asm and on the voodoo side in voodoo_lib.h has been greatly improved, there's now a huge amount of memory available for patch code and there's no need to use code caves anymore 🙂
